// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/scan-domain.ts
import { createClient } from "npm:@supabase/supabase-js@^2.78.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var DEFAULT_PROMPTS = [
  "What are the best tools to check AI search visibility?",
  "Which platforms track brand mentions in ChatGPT and Perplexity?",
  "Top AI visibility monitoring tools for SaaS companies"
];
var scan_domain_default = defineTool({
  name: "scan_domain",
  title: "Scan a domain for AI visibility",
  description: "Run an AI visibility scan for a domain against ChatGPT, Gemini, Perplexity and web search. Returns the score, per-prompt mentions and citations, and top competitors.",
  inputSchema: {
    domain: z.string().min(3).describe("The domain to scan, e.g. example.com"),
    prompts: z.array(z.string().min(3)).max(10).optional().describe("Optional list of prompts to test (max 10). Defaults to a small built-in prompt set."),
    market: z.string().optional().describe("Market/locale code, e.g. 'us' or 'gb'. Defaults to 'us'.")
  },
  annotations: { readOnlyHint: false, openWorldHint: true },
  handler: async ({ domain, prompts, market }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const promptsText = (prompts && prompts.length ? prompts : DEFAULT_PROMPTS).join("\n");
    const { data, error } = await supabase.functions.invoke("scan", {
      body: { domain, promptsText, market: market ?? "us" }
    });
    if (error) {
      return { content: [{ type: "text", text: `Scan failed: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data).slice(0, 8e3) }],
      structuredContent: { scan: data }
    };
  }
});

// src/lib/mcp/tools/list-scans.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.78.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_scans_default = defineTool2({
  name: "list_scans",
  title: "List my recent AI visibility scans",
  description: "List the signed-in user's most recent AI visibility scans (id, domain, score, created_at).",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("How many scans to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("scans").select("id, project_domain, score, market, created_at, is_auto_scan").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { scans: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-scan.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.78.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_scan_default = defineTool3({
  name: "get_scan",
  title: "Get a scan by ID",
  description: "Fetch a single AI visibility scan by ID, including per-prompt results (mentions, citations, competitors).",
  inputSchema: {
    scanId: z3.string().uuid().describe("The scan's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true },
  handler: async ({ scanId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data: scan, error } = await supabase.from("scans").select("*").eq("id", scanId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!scan) return { content: [{ type: "text", text: "Scan not found" }], isError: true };
    const { data: results } = await supabase.from("scan_results").select("*").eq("scan_id", scanId);
    const payload = { scan, results: results ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload).slice(0, 8e3) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-saved-domains.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.78.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_saved_domains_default = defineTool4({
  name: "list_saved_domains",
  title: "List my saved domains",
  description: "List the signed-in user's saved domains being tracked for AI visibility.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("saved_domains").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { domains: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sxcsbqglcmwbueztpvei";
var mcp_default = defineMcp({
  name: "ai-mention-you-mcp",
  title: "AI Mention You",
  version: "0.1.0",
  instructions: "Tools for AI Mention You. Run and read AI visibility scans (ChatGPT, Gemini, Perplexity) for the signed-in user's domains, and list their saved domains and past scans.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [scan_domain_default, list_scans_default, get_scan_default, list_saved_domains_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
